"""Initial migration

Revision ID: 97a80b7c7d5a
Revises: 
Create Date: 2025-03-19 22:50:56.713766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a80b7c7d5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survived', sa.Boolean(), nullable=False),
    sa.Column('pclass', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('siblings_spouses', sa.Integer(), nullable=False),
    sa.Column('parents_children', sa.Integer(), nullable=False),
    sa.Column('fare', sa.Float(), nullable=False),
    sa.Column('ticket', sa.String(), nullable=True),
    sa.Column('cabin', sa.String(), nullable=True),
    sa.Column('embarked', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passengers_id'), 'passengers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passengers_id'), table_name='passengers')
    op.drop_table('passengers')
    # ### end Alembic commands ###
